restaurant/urls.py
from django.urls import path

from restaurant.views import (index,
                              FoodListView,
                              DishTypeCreateView,
                              FoodDetailView,
                              CookerDetailView,
                              DishCreateView,
                              CookerCreateView,
                              FoodUpdateView, FoodDeleteView,
                              )

urlpatterns = [
    path("", index, name="index"),
    path("category/create/", DishTypeCreateView.as_view(), name="category-create"),
    path("category/<int:pk>/", FoodListView.as_view(), name="food-list"),
    path("category/dish/<int:pk>/", FoodDetailView.as_view(), name="food-detail"),
    path("category/dish/<int:pk>/update/", FoodUpdateView.as_view(), name="food-update"),
    path("category/dish/<int:pk>/delete/", FoodDeleteView.as_view(), name="food-delete"),
    path("category/dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("accounts/signin/", CookerCreateView.as_view(), name="account-create"),
    path("accounts/<int:pk>/", CookerDetailView.as_view(), name="account-detail"),
]

app_name = "restaurant"

restaurant_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", include("restaurant.urls", namespace="catalog")),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.username}, ({self.first_name} {self.last_name})"


class Dish(models.Model):
    name = models.CharField(max_length=63)
    description = models.TextField(max_length=255)
    price = models.IntegerField()
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(
        Cook
    )

    def __str__(self):
        return f"{self.name}"

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from restaurant.models import DishType, Dish, Cook


class DishTypeCreationForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = ["name"]


class DishCreationForm(forms.ModelForm):
    dish_type = forms.ModelChoiceField(
        queryset=DishType.objects.all(),
    )
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_license_number(self.cleaned_data["years_of_experience"])


def validate_license_number(years):
    if years < 0:
        raise ValidationError("Min years value is 0")
    return years


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by dish name..."})
    )

restaurant/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from restaurant.forms import DishTypeCreationForm, DishCreationForm, CookerCreationForm, DishSearchForm
from restaurant.models import DishType, Dish, Cook


def index(request):
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()
    num_cookers = Cook.objects.count()
    dish_type_list = DishType.objects.all()

    context = {
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_cookers": num_cookers,
        "dish_type_list": dish_type_list

    }

    return render(request, "restaurant/index.html", context=context)


class FoodListView(generic.ListView):
    model = Dish
    context_object_name = "dishes_list"
    template_name = "restaurant/dishes_list.html"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        dish_pk = self.kwargs["pk"]
        dish_type = get_object_or_404(DishType, pk=dish_pk)
        context["dish_type"] = dish_type
        context["dish_type_list"] = DishType.objects.all()
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(initial={
            "name": name,
        })
        return context

    def get_queryset(self):
        dish_type = self.kwargs["pk"]
        queryset = Dish.objects.filter(dish_type__id=dish_type)
        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class FoodDetailView(generic.DetailView):
    template_name = "restaurant/dish_detail.html"
    context_object_name = "dish"
    model = Dish


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = DishTypeCreationForm
    success_url = reverse_lazy("catalog:index")
    template_name = "restaurant/catalog_create.html"


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = DishCreationForm
    success_url = reverse_lazy("catalog:index")
    template_name = "restaurant/dish_form.html"


class CookerCreateView(generic.CreateView):
    model = Cook
    form_class = CookerCreationForm
    template_name = "registration/sign_in.html"
    success_url = reverse_lazy("login")


class CookerDetailView(generic.DetailView):
    model = Cook
    template_name = "restaurant/cooker_detail.html"


class FoodUpdateView(LoginRequiredMixin, generic.UpdateView):
    form_class = DishCreationForm
    model = Dish
    success_url = reverse_lazy("catalog:index")
    template_name = "restaurant/dish_form.html"


class FoodDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("catalog:index")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Restaurant project</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
{% block sidebar %}{% include "includes/sidebar.html" %}{% endblock %}
{% block content %}{% endblock %}
{% block pagination %}{% endblock %}
{% block footer %}{% include "includes/footer.html" %}{% endblock %}
{% block js_scripts %}{% include "includes/js_scripts.html" %}{% endblock %}
</body>
</html>

templates/includes/footer.html
<footer class="footer fixed-bottom" style="background-color: whitesmoke">
  <div class="d-flex flex-column flex-sm-row justify-content-between py-2 border-top">
    <p>&copy; 2022 Company, Inc. All rights reserved.</p>
    <ul class="list-unstyled d-flex">
      <li class="ms-3"><a class="link-dark" href="#"><i class="fa-brands fa-facebook fa-2x"></i></a></li>
      <li class="ms-3"><a class="link-dark" href="#"><i class="fa-brands fa-instagram fa-2x"></i></a></li>
      <li class="ms-3"><a class="link-dark" href="#"><i class="fa-brands fa-x-twitter fa-2x"></i></a></li>
    </ul>
  </div>
</footer>

templates/includes/js_scripts.html
<script src="https://kit.fontawesome.com/70dbb55011.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="text-center mb-3">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="??{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endif %}

templates/includes/search.html
{% load crispy_forms_filters %}
<div class="text-center mb-3">
  <form action="" method="get" class="form-inline d-inline-flex">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>
</div>

templates/includes/sidebar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'catalog:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'catalog:account-detail' pk=user.id %}">Profile</a>
        {% endif %}
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Catalog
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for dish_type in dish_type_list %}
            <a class="dropdown-item" href="{% url 'catalog:food-list' pk=dish_type.id %}">{{ dish_type.name.upper }}</a>
          {% endfor %}
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0 menu-link">
      {% if user.is_authenticated %}
        <li class="list-group-item">Cooker: <a
            href="{% url 'catalog:account-detail' pk=user.id %}">{{ user.get_username }}</a></li>
        <li class="list-group-item"><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
      {% else %}
        <li class="list-group-item"><a href="{% url 'login' %}?next={{ request.path }}">Login<i
            class="fa-solid fa-right-to-bracket"></i></a></li>
        <li class="list-group-item"><a href="{% url 'restaurant:account-create' %}?next={{ request.path }}">Sign In</a>
        </li>
      {% endif %}
    </form>
  </div>
</nav>

templates/restaurant/catalog_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container py-5" style="width: 40%">
    <h3>Create Dish Type</h3>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit">
    </form>
  </div>
{% endblock %}

templates/restaurant/cooker_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h1>Cooker detail:</h1>
    <ul class="list-group">
      <li class="list-group-item"><strong>Cooker Username: </strong> {{ cook.username }}</li>
      <li class="list-group-item"><strong>Cooker Name: </strong> {{ cook.first_name }}</li>
      <li class="list-group-item"><strong>Cooker Last Name: </strong> {{ cook.last_name }}</li>
      <li class="list-group-item"><strong>Cooker Email: </strong> {{ cook.email }}</li>
      <li class="list-group-item"><strong>Cooker experience: </strong> {{ cook.years_of_experience }}</li>
      <li class="list-group-item">
        <strong>Cookers' dishes:</strong>
        <ul>
          {% for dish in cook.dish_set.all %}
            <li>{{ dish.name }}</li>
          {% endfor %}
        </ul>
      </li>
    </ul>
  </div>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container py-5">
    <h1>Delete Dish: {{ dish.name }}?</h1>
    <p>Are you sure you want to delete this item from the list? Please be aware that deleting this item will have
      consequences</p>
    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </div>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h1>Dish detail: {{ dish.name }} <a href="{% url 'catalog:food-update' pk=dish.id %}">
      <button type="button" class="btn btn-primary">Update</button>
    </a></h1>
    <ul class="list-group">
      <li class="list-group-item"><strong>Dish Name:</strong> {{ dish.name }}</li>
      <li class="list-group-item"><strong>Dish Type:</strong> {{ dish.dish_type }}</li>
      <li class="list-group-item"><strong>Dish Price:</strong> {{ dish.price }}</li>
      <li class="list-group-item"><strong>Dish Description:</strong> {{ dish.description }}</li>
      <li class="list-group-item">
        <strong>Cookers who made this dish:</strong>
        <ul>
          {% for cooker in dish.cookers %}
            <li>{{ cooker.name }}</li>
          {% endfor %}
        </ul>
      </li>
      <li class="list-group-item"><strong>Dish Delete:</strong><a href="{% url 'catalog:food-delete' pk=dish.id %}">
        <button type="button" class="btn btn-danger">Delete</button>
      </a></li>
    </ul>
  </div>
{% endblock %}

templates/restaurant/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <div class="container py-5">
    <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
    <form action="" method="post" class="my-form">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary btn-block">Submit</button>
    </form>
  </div>
{% endblock %}

templates/restaurant/dishes_list.html
{% extends "base.html" %}
  {% load crispy_forms_filters %}
{% block content %}
<div class="container-list">
  <h3><a href="{% url 'restaurant:dish-create' %}"><button type="button" class="btn btn-primary">Create Dish</button></a> {{ dish_type.name.capitalize }} List:</h3>
  {% include "includes/search.html" %}
  <ul class="dish-list">
    {% for dish in dishes_list %}
      <li class="dish-item">
        {{ dish_type.name.capitalize }} name: {{ dish.name }}, price: {{ dish.price }}
        <a href="{% url 'catalog:food-detail' pk=dish.id %}" class="detail-link">Detail</a>
      </li>
    {% endfor %}
  </ul>
{% include "includes/pagination.html" %}
</div>
{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}
{% block content %}
  {#  <h3>Main page</h3>#}
  {#  <p>Num of Cookers: {{ num_cookers }}</p>#}
  {#  <p>Num of Dish Tpes: {{ num_dish_types }}#}
  {#    <a href="{% url 'restaurant:category-create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Create Dish Type</a></p>#}
  {#  <p>Num of Dishes: {{ num_dishes }}#}
  {#  <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Create Dish</a></p></p>#}
  <main role="main">

    <section class="jumbotron text-center">
      <div class="container">
        <h1>Culinary forum</h1>
        <p class="lead text-muted">Culinary Atelier: Sharing and Inspiring with Delicacies
        <p>
      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">

        <div class="row">
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                   role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                   focusable="false">
                <rect width="100%" height="100%" fill="#55595c"/>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">Count of Cookers: {{ num_cookers }}</text>
              </svg>

              <div class="card-body">
                <p class="card-text">
                  {% if user.is_authenticated %}
                    <p>You are one of the chefs!</p>
                  {% else %}
                    <p>Please register to become our chef:</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <a href="{% url 'login' %}">
                          <button type="button" class="btn btn-sm btn-outline-secondary">Login</button>
                        </a>
                      </div>
                    </div>
                  {% endif %}
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                   role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                   focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"/>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">Count of Dish Types: {{ num_dish_types }}</text>
              </svg>

              <div class="card-body">
                <p class="card-text">Create your own Food Category:
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'restaurant:category-create' %}">
                      <button type="button" class="btn btn-sm btn-outline-secondary">Create Dish Type</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                   role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                   focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c"/>
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">Count of dishes: {{ num_dishes }}</text>
              </svg>

              <div class="card-body">
                <p class="card-text">Create your own dish: </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a href="{% url 'restaurant:dish-create' %}">
                      <button type="button" class="btn btn-sm btn-outline-secondary">Create Dish</button>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

{% endblock %}